### ISSUE TITLE
Connecting to kerberized Impala

### ISSUE THREAD

**Issue by zhujiaqi** [beltran/gosasl#7]
Hello! Firstly, Thank you for this wonderful project that saved my days!

I was trying to write a client to connect to a kerberized Impala daemon in a CDH cluster, using its Thrift protocal. 

My goal was to modify this [impalathing](https://github.com/koblas/impalathing), adding sasl_transport from your gohive project, which requires gosasl. That's why im here.

After a frustrating day with the believe that I was getting very close to get this working, I could not.

"The maximum packet length can't be zero. The server doesn't support GSSAPI" was all i got.

Just before giving up I was looking at the source of this project and decided to remove this fail-safe check to see what will happen...and surprisingly enough my code worked.

After several days, the code seems working alright. However I still don't know the root of this cause, so I'm here for the answer.

What's the purpose of these lines. Any risk if I remove them?

Thanks for your time.

```
--- a/gssapi.go
+++ b/gssapi.go
@@ -86,9 +86,9 @@ func (m *GSSAPIMechanism) step(challenge []byte) ([]byte, error) {
                qopBits := data[0]
                data[0] = 0
                m.serverMaxLength = int(binary.BigEndian.Uint32(data))
-               if m.serverMaxLength == 0 {
+               /* if m.serverMaxLength == 0 {
                        return nil, fmt.Errorf("The maximum packet length can't be zero. The server doesn't support GSSAPI")
-               }
+               }*/
```

CDH version 5.11.0 
go version go1.9.4 
linux/amd64 centos 7

**Comment by beltran** [comment]
Hello @zhujiaqi, sorry you ran into so much trouble. The reason that comparison is there is because of this line `The client verifies that the server maximum buffer is 0 if the server does not advertise support for any security layer` in https://tools.ietf.org/html/rfc4752 but I think now after rereading I misinterpreted it and it's a bug in the driver. Also [other sasl libraries don't do this check](https://github.com/thobbs/pure-sasl/blob/master/puresasl/mechanisms.py#L527).

I don't want to take ownership of you work so feel free to open a PR and I'll merge it.

**Comment by zhujiaqi** [comment]
Thank you very much, PR submitted.

**Comment by beltran** [comment]
Thank you for catching this and the PR!
